baseurl = "/"
languageCode = "en-us"
title = "Michael Fuchs Python"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/MFuchs1989/"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/michael-fuchs-139172131/"
[[menu.main]]
    name = "XING"
    url = "https://www.xing.com/profile/Michael_Fuchs426/cv?sc_o=mxb_p"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/Stat_Michael"
[[menu.main]]
    name = "zum R-Blog"
    url = "https://michael-fuchs.netlify.com/"
[[menu.main]]
    name = "Tag Archive"
    url = "/Tag_Archive/"


[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "MFuchs.png"
    width = 50
    height = 50
    alt = "MFuchs"

