---
title: SQL
author: Michael Fuchs
date: '2021-03-24'
slug: sql
categories:
  - R
tags:
  - R Markdown
output:
  blogdown::html_page:
    toc: true
    toc_depth: 5
---


# 1 Introduction 


Long time no hear. But I have not been idle. 
I have dedicated myself to another project in between: **SQL**


I have built a new homepage for this again. You can find it here: [Michael Fuchs SQL](https://michael-fuchs-sql.netlify.app/)



# 2 Chapters covered

At this point I link the topics covered with the respective posts.


## 2.1 Theoretical Background

+ [Normalization of Databases](https://michael-fuchs-sql.netlify.app/2021/05/16/normalization-of-databases/)
+ [Types of SQL Commands](https://michael-fuchs-sql.netlify.app/2021/05/13/types-of-sql-commands/)
+ [Entity-Relationship-Diagram (ERD)](https://michael-fuchs-sql.netlify.app/2021/03/03/entity-relationship-diagram-erd/)
+ [Types of Databases](https://michael-fuchs-sql.netlify.app/2021/03/01/types-of-databases/)



## 2.2 Setup and Relationships of Tables


+ [Create a n:m Relationship](https://michael-fuchs-sql.netlify.app/2021/03/16/create-a-m-m-relationship/)
+ [Create a 1:m Relationship](https://michael-fuchs-sql.netlify.app/2021/03/13/create-a-1-m-relationship/)
+ [Create a 1:1 Relationship](https://michael-fuchs-sql.netlify.app/2021/03/10/create-a-1-1-relationship/)
+ [Create a Database](https://michael-fuchs-sql.netlify.app/2021/03/07/create-a-database/)



## 2.3 SQL Server specific Posts

+ [How to Backup a Database](https://michael-fuchs-sql.netlify.app/2021/08/01/how-to-backup-a-database/)
+ [Local and Global Temp Tables](https://michael-fuchs-sql.netlify.app/2021/05/10/local-and-global-temp-tables/)
+ [Read and write to files](https://michael-fuchs-sql.netlify.app/2021/03/20/read-and-write-to-files/)
+ [Aliases](https://michael-fuchs-sql.netlify.app/2021/03/19/aliases/)



## 2.4 Data Science

+ [Update a Table](https://michael-fuchs-sql.netlify.app/2021/05/08/update-a-table/)
+ [Generation of new Tables](https://michael-fuchs-sql.netlify.app/2021/05/06/generation-of-new-tables/)
+ [Views](https://michael-fuchs-sql.netlify.app/2021/05/03/views/)
+ [Union](https://michael-fuchs-sql.netlify.app/2021/04/29/union/)
+ [Joins](https://michael-fuchs-sql.netlify.app/2021/04/21/joins/)
+ [Window Functions](https://michael-fuchs-sql.netlify.app/2021/04/12/window-functions/)
+ [Working with Dates](https://michael-fuchs-sql.netlify.app/2021/04/07/working-with-dates/)
+ [String Functions](https://michael-fuchs-sql.netlify.app/2021/04/03/string-functions/)
+ [Subqueries](https://michael-fuchs-sql.netlify.app/2021/04/01/subqueries/)
+ [Data Manipulation](https://michael-fuchs-sql.netlify.app/2021/03/29/data-manipulation/)
+ [Data Aggregation](https://michael-fuchs-sql.netlify.app/2021/03/26/data-aggregation/)
+ [Data Wrangling](https://michael-fuchs-sql.netlify.app/2021/03/23/data-wrangling/)


## 2.5 SQL Tools

+ [Data Types Settings in Oracle Data Modeler](https://michael-fuchs-sql.netlify.app/2021/10/01/data-types-settings-in-oracle-data-modeler/)
+ [Oracle SQL Developer Data Modeler](https://michael-fuchs-sql.netlify.app/2021/09/01/oracle-sql-developer-data-modeler/)

# 3 Conclusion


Here I have created an overview of the topics I have covered with the programming language SQL. 


